server:
  port: ${APPLICATION_PORT:8080}
  servlet:
    context-path: /@project.artifactId@
spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    fullname: @project.name@
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:passwordnyaPostgres}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        id:
          new_generator_mappings: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    encoding: UTF-8
    enabled: true
    baseline-on-migrate: true
    check-location: true
    locations: classpath:/db/migration/postgresql
    clean-disabled: false
    clean-on-validation-error: true
    connect-retries: 2
  thymeleaf:
    enable-spring-el-compiler: true
    enabled: true
    cache: false
    check-template: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
    servlet:
      content-type: text/html
    check-template-location: true
    template-resolver-order: 0
logging:
  level:
    org.springframework: ERROR
    com.tabeldata: DEBUG
  file: ${spring.application.name}.log
